#!/bin/bash

# Copyright (c) 2013 Artem Shinkarov <artyom.shinkaroff@gmail.com>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

arg_test () { # Filter out arguments that are invalid
    local usage='Usage: i3lock-wrapper [-v] [-n] [-b] [-d] [-p win|default] [-u]'
    local valid_opts=('-v' '--version' '-n' '--nofork' '-b' '--beep' '-d' '--dpms' '-u' '--no-unlock-indicator' '-p' '--pointer')

    while [[ $# > 0 ]]; do
        flag_good=0

        for valid_opt in ${valid_opts[@]}; do
            if [[ "${1/=*/}" == "$valid_opt" ]]; then
                flag_good=1
                [[ $1 == '-p' ]] && shift # Ignore pointer type
            fi
        done

        if [[ $flag_good -ne 1 ]]; then
            echo $usage
            exit
        fi

        shift
    done
}

arg_test $@

file1=$(mktemp --tmpdir i3lock-wrapper-XXXXXXXXXX.png)
file2=$(mktemp --tmpdir i3lock-wrapper-XXXXXXXXXX.png)

scrot -d0 "$file1"
convert "$file1" -blur 0x3 "$file2"
i3lock -i "$file2" $@

trap "rm '$file1' '$file2'" EXIT
